dist: xenial

language: python
python: '3.11'

branches:
  only:
    - master

before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  # - source $HOME/.poetry/env
  # - source $HOME/.local/bin
install:
  - poetry install
script:
  - poetry build
deploy:
  - provider: script
    skip_cleanup: true
    script: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
    on:
      branch: master
